# Initial content coming from
# https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
          - id: check-json
          ## The generated types/requests/responses are huge!
          #-   id: check-added-large-files
          - id: check-yaml
          - id: debug-statements
          ## Disabled because it compains about additional modules used in testing
          #-   id: name-tests-test
          #    args: ['--django']
          - id: requirements-txt-fixer
          - id: check-ast
          - id: check-builtin-literals
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-vcs-permalinks
          - id: check-xml
          - id: file-contents-sorter
          - id: forbid-new-submodules
          - id: mixed-line-ending
          - id: pretty-format-json
          - id: sort-simple-yaml

    # ------------------------------------------------------------------------------------------------------------------ #
    # Ruff is an extremely fast Python linter and formatter, written in Rust. It is intended to replace Flake8, isort,
    # pydocstyle, yesqa, eradicate, pyupgrade, autoflake, and black.
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.12.4
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: https://github.com/pre-commit/pre-commit
      rev: v3.7.0
      hooks:
          - id: validate_manifest

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.20.0
      hooks:
          - id: pyupgrade
            args: [--py38-plus]

    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.2.0
      hooks:
          - id: add-trailing-comma

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.17.0
      hooks:
          - id: mypy
            additional_dependencies: [types-attrs]

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0 # or specific git tag
      hooks:
          - id: shfmt
# end
