# Config file for automatic testing at travis-ci.com

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: pip install poetry tox-travis codecov
script: tox
after_success: codecov

stages:
  - test
  - lint
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  #include:
  #  - stage: test
  #    python: 3.8
  #    env: TOXENV=docs
  #  - stage: lint
  #    python: 3.8
  #    env: TOXENV=black
  #  - python: 3.8
  #    env: TOXENV=mypy
  #  - python: 3.8
  #    env: TOXENV=pylint
  #  - python: 3.8
  #    env: TOXENV=vulture
  #  - stage: deploy
  #    python: 3.8
  #    install: true
  #    script: true
  #    after_success: true

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config pypi-token.pypi $PYPI_PASSWORD

deploy:
- provider: script
  script: poetry publish --build
  on:
    branch: master
    tags: true

# end
