site_name: broadworks_ocip
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://broadworks-ocip.github.io"
repo_url: "https://github.com/broadworks-ocip/broadworks_ocip"
repo_name: "broadworks-ocip/broadworks_ocip"

nav:
    - Overview: index.md
    - Usage: usage.md
    - API Reference:
          - API: api/api.md
          - Base Classes: api/base.md
          - Exceptions: api/exceptions.md
          - Requests: api/requests.md
          - Responses: api/responses.md
          - Types: api/types.md
    - Internal Design: internals.md
    - Contributing: contributing.md
    - Changelog: changelog.md
    - License: license.md
    - To Do: todo.md

theme:
    name: material
    features:
        - navigation.instant
        - navigation.expand

extra_css:
    - css/mkdocstrings.css

markdown_extensions:
    - pymdownx.highlight:
          linenums_style: pymdownx.inline
    - pymdownx.magiclink
    - pymdownx.superfences
    - markdown_include.include
    - md_in_html

plugins:
    - search
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  rendering:
                      show_source: true
                  selection:
                      new_path_syntax: yes
                      filters:
                          - "!^_" # exlude all members starting with _
                          - "^__init__$" # but always include __init__ modules and methods
          watch:
              - broadworks_ocip
# end
