name: Generate documentation

on:
    workflow_call:

jobs:
    generate_docs:
        name: Generate documentation
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Setup Git Commit Info
              run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'

            - name: Install UV
              uses: astral-sh/setup-uv@v6
              with:
                version: ">=0.5.24"
            # Temporarily disabled due to issues with mkdocs-gh-deploy
            # - name: Publish docs
            #   run: uv run mkdocs gh-deploy
