name: Run Complete Tests

on:
    workflow_call:

jobs:
    full_tests:
        runs-on: ubuntu-latest
        name: NOX test run
        steps:
            - uses: actions/checkout@v4
            - uses: excitedleigh/setup-nox@v2.0.0
            - name: Install UV
              uses: astral-sh/setup-uv@v6
              with:
                version: ">=0.5.24"

            - run: nox
