name: Run Tests

on:
    workflow_call:

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Install UV
              uses: astral-sh/setup-uv@v6
              with:
                version: ">=0.5.24"

            - name: Run tests
              run: make test
