name: Run Tests

on:
    workflow_call:

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Set up repository
              uses: nigelm/gh_actions_python_poetry_setup@v2
              with:
                  python-version: 3.10.10
                  poetry-version: 1.3.1

            - name: Run tests
              run: make test
# end
