name: Upload To Pypi

on:
    workflow_call:
        secrets:
            PYPI_TOKEN:
                description: The pypi token to use for authentication
                required: true

jobs:
    upload:
        name: Upload To Pypi
        runs-on: ubuntu-latest
        environment: deployment
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Install UV
              uses: astral-sh/setup-uv@v6
              with:
                version: ">=0.5.24"

            - name: Build package
              run: |
                uv build

            - name: Publish package on PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                user: __token__
                password: ${{ secrets.PYPI_TOKEN }}
