# basic set of tests
name: Deploy
on:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: nigelm/broadworks_ocip/.github/workflows/_test.yml@master
  lint:
    uses: nigelm/broadworks_ocip/.github/workflows/_linting.yml@master

  upload:
    needs: [tests, lint]
    uses: nigelm/broadworks_ocip/.github/workflows/_upload.yml@master
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  docs:
    needs: [tests, lint]
    uses: nigelm/broadworks_ocip/.github/workflows/_docs.yml@master


# end
