name: Overall Release Process
on: workflow_dispatch
jobs:
    tests:
        uses: ./.github/workflows/_test.yml
    lint:
        uses: ./.github/workflows/_linting.yml
    ## NOX test removed because the workflow currently broken (fails to install)
    # full_test:
    #   needs: [tests, lint]
    #   uses: ./.github/workflows/_full_tests.yml

    release:
        runs-on: ubuntu-latest
        concurrency: release
        # needs: full_test
        needs: [tests, lint]
        environment: deployment

        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                token: ${{ secrets.GH_DEPLOY_TOKEN }}

            #----------------------------------------------
            # release
            #----------------------------------------------
            - name: Semantic Release
              env:
                  GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
              run: |
                  # source .venv/bin/activate
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  uv run semantic-release publish

# end
